# Generated by Django 5.0.1 on 2024-01-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('price', models.FloatField(help_text='Price in Rial')),
                ('latitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor.motorstation')),
                ('longitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='motor.motorstation')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nationalid', models.CharField(max_length=10)),
                ('reservation_code', models.CharField(max_length=8, unique=True)),
                ('Motor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motor.motorstation')),
            ],
        ),
    ]
