# Generated by Django 5.0.1 on 2024-01-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('phone_number', models.CharField(max_length=11)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
