# Generated by Django 5.0.1 on 2024-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=11)),
                ('cvv2_number', models.CharField(max_length=4)),
                ('time', models.DateTimeField()),
                ('code', models.CharField(max_length=4)),
            ],
        ),
    ]
