# Generated by Django 5.0.1 on 2024-01-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_sender', models.TextField()),
                ('address_Receiver', models.TextField()),
                ('name_product', models.CharField(max_length=400)),
                ('price', models.FloatField(help_text='Price in Rial')),
                ('price_transfer', models.FloatField(help_text='Price in Rial')),
            ],
        ),
    ]
